import { ThemeProvider } from "./theme-provider";

export const metadata = {
  title: "Servisso Cars",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{
          height: "100vh",
          margin: 0,
          fontFamily: '"Inter", sans-serif',
        }}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
